//! Inline diagnostic suppressions.
//!
//! Grammar (all forms are line comments starting with `// sysml-validate:`):
//!
//! ```text
//! // sysml-validate: disable=SYSML041
//! // sysml-validate: disable=SYSML041,SYSML040
//! // sysml-validate: disable=all
//! // sysml-validate: disable-next-line=SYSML041
//! ```
//!
//! "Same-line" directives apply to diagnostics on the same line as the
//! comment. "Next-line" directives apply to the next non-blank line. A
//! directive may name a comma-separated rule list, or `all`.

use crate::diag::{Diagnostic, Position, Severity};
use std::path::Path;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Suppression {
    pub directive_line: usize,
    pub directive_column: usize,
    pub applies_to_line: SuppressionScope,
    pub rules: SuppressionRules,
    pub used: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuppressionScope {
    SameLine(usize),
    NextNonBlankLine { directive_line: usize },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum SuppressionRules {
    All,
    Specific(Vec<String>),
}

#[derive(Clone, Debug)]
pub struct DirectiveParseError {
    pub line: usize,
    pub column: usize,
    pub message: String,
}

/// Parse a single `// sysml-validate:` comment body.
///
/// `body` is the comment text after the leading `//`, with leading
/// whitespace already trimmed. `line` and `column` mark the start of the
/// comment in the source.
pub fn parse_directive(
    line: usize,
    column: usize,
    body: &str,
) -> Option<Result<Suppression, DirectiveParseError>> {
    let body = body.trim();
    let payload = body.strip_prefix("sysml-validate:")?.trim();

    let (verb, rules_text) = match payload.split_once('=') {
        Some((verb, rules)) => (verb.trim(), rules.trim()),
        None => {
            return Some(Err(DirectiveParseError {
                line,
                column,
                message: format!(
                    "expected 'disable=...' or 'disable-next-line=...' in '{payload}'",
                ),
            }));
        }
    };

    let scope = match verb {
        "disable" => SuppressionScope::SameLine(line),
        "disable-next-line" => SuppressionScope::NextNonBlankLine {
            directive_line: line,
        },
        other => {
            return Some(Err(DirectiveParseError {
                line,
                column,
                message: format!("unknown directive '{other}'; expected 'disable' or 'disable-next-line'"),
            }));
        }
    };

    let rules = if rules_text.eq_ignore_ascii_case("all") {
        SuppressionRules::All
    } else if rules_text.is_empty() {
        return Some(Err(DirectiveParseError {
            line,
            column,
            message: "directive must list at least one rule code or 'all'".to_string(),
        }));
    } else {
        let codes: Vec<String> = rules_text
            .split(',')
            .map(|item| item.trim().to_string())
            .filter(|item| !item.is_empty())
            .collect();
        if codes.is_empty() {
            return Some(Err(DirectiveParseError {
                line,
                column,
                message: "rule list is empty".to_string(),
            }));
        }
        SuppressionRules::Specific(codes)
    };

    Some(Ok(Suppression {
        directive_line: line,
        directive_column: column,
        applies_to_line: scope,
        rules,
        used: false,
    }))
}

/// Resolve each suppression's target line and mark matching diagnostics
/// as suppressed in place. Returns any `SYSML050` "unused suppression"
/// diagnostics generated by directives that didn't match anything.
///
/// `non_blank_lines` is the sorted list of lines (1-based) that contain at
/// least one token after the scanner pass; "next non-blank line" maps to
/// the smallest entry strictly greater than the directive's line.
pub fn apply_suppressions(
    diagnostics: &mut [Diagnostic],
    suppressions: &mut [Suppression],
    non_blank_lines: &[usize],
    path: &Path,
) -> Vec<Diagnostic> {
    let resolved_targets: Vec<Option<usize>> = suppressions
        .iter()
        .map(|suppression| match suppression.applies_to_line {
            SuppressionScope::SameLine(line) => Some(line),
            SuppressionScope::NextNonBlankLine { directive_line } => non_blank_lines
                .iter()
                .copied()
                .find(|line| *line > directive_line),
        })
        .collect();

    for diagnostic in diagnostics.iter_mut() {
        if diagnostic.is_suppressed() {
            continue;
        }
        let Some(diagnostic_line) = diagnostic.position.as_ref().map(|position| position.line)
        else {
            continue;
        };
        for (suppression, target_line) in suppressions.iter_mut().zip(resolved_targets.iter()) {
            let Some(target_line) = target_line else {
                continue;
            };
            if *target_line != diagnostic_line {
                continue;
            }
            let matches_rule = match &suppression.rules {
                SuppressionRules::All => true,
                SuppressionRules::Specific(codes) => codes.iter().any(|code| code == diagnostic.code),
            };
            if matches_rule {
                suppression.used = true;
                diagnostic.suppression = Some(format!(
                    "Suppressed by directive at line {} column {}.",
                    suppression.directive_line, suppression.directive_column
                ));
                break;
            }
        }
    }

    let mut produced = Vec::new();
    for suppression in suppressions.iter() {
        if !suppression.used {
            produced.push(Diagnostic::new(
                Severity::Warning,
                "SYSML050",
                "Suppression directive did not match any diagnostic.",
                path,
                Some(Position {
                    line: suppression.directive_line,
                    column: suppression.directive_column,
                }),
            ));
        }
    }

    produced
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diag::{Diagnostic, Position, Severity};
    use std::path::PathBuf;

    fn make_diag(line: usize, code: &'static str) -> Diagnostic {
        Diagnostic::new(
            Severity::Error,
            code,
            "test",
            &PathBuf::from("/x"),
            Some(Position { line, column: 1 }),
        )
    }

    #[test]
    fn parses_same_line_specific() {
        let result = parse_directive(5, 1, "sysml-validate: disable=SYSML041").unwrap().unwrap();
        assert!(matches!(result.applies_to_line, SuppressionScope::SameLine(5)));
        assert_eq!(
            result.rules,
            SuppressionRules::Specific(vec!["SYSML041".into()])
        );
    }

    #[test]
    fn parses_disable_all() {
        let result = parse_directive(5, 1, "sysml-validate: disable=all").unwrap().unwrap();
        assert_eq!(result.rules, SuppressionRules::All);
    }

    #[test]
    fn parses_next_line() {
        let result = parse_directive(5, 1, "sysml-validate: disable-next-line=SYSML041")
            .unwrap()
            .unwrap();
        assert!(matches!(
            result.applies_to_line,
            SuppressionScope::NextNonBlankLine { directive_line: 5 }
        ));
    }

    #[test]
    fn parses_multiple_rules() {
        let result = parse_directive(5, 1, "sysml-validate: disable=SYSML041,SYSML040")
            .unwrap()
            .unwrap();
        assert_eq!(
            result.rules,
            SuppressionRules::Specific(vec!["SYSML041".into(), "SYSML040".into()])
        );
    }

    #[test]
    fn returns_none_for_non_directive_comments() {
        assert!(parse_directive(5, 1, "just a regular comment").is_none());
    }

    #[test]
    fn rejects_unknown_verb() {
        let err = parse_directive(5, 1, "sysml-validate: enable=SYSML041")
            .unwrap()
            .unwrap_err();
        assert!(err.message.contains("unknown directive"));
    }

    #[test]
    fn rejects_empty_rule_list() {
        let err = parse_directive(5, 1, "sysml-validate: disable=")
            .unwrap()
            .unwrap_err();
        assert!(err.message.contains("at least one rule code"));
    }

    #[test]
    fn suppresses_same_line() {
        let mut diagnostics = vec![make_diag(5, "SYSML041")];
        let mut suppressions = vec![Suppression {
            directive_line: 5,
            directive_column: 30,
            applies_to_line: SuppressionScope::SameLine(5),
            rules: SuppressionRules::Specific(vec!["SYSML041".into()]),
            used: false,
        }];
        let unused = apply_suppressions(&mut diagnostics, &mut suppressions, &[5], Path::new("/x"));
        // Diagnostic is KEPT and marked as suppressed (Batch C: SARIF
        // emits suppressions[]; counts and exit code still ignore them).
        assert_eq!(diagnostics.len(), 1);
        assert!(diagnostics[0].is_suppressed());
        assert!(unused.is_empty());
        assert!(suppressions[0].used);
    }

    #[test]
    fn unused_suppression_produces_sysml050() {
        let mut diagnostics: Vec<Diagnostic> = Vec::new();
        let mut suppressions = vec![Suppression {
            directive_line: 5,
            directive_column: 1,
            applies_to_line: SuppressionScope::SameLine(5),
            rules: SuppressionRules::Specific(vec!["SYSML041".into()]),
            used: false,
        }];
        let unused = apply_suppressions(&mut diagnostics, &mut suppressions, &[5], Path::new("/x"));
        assert_eq!(unused.len(), 1);
        assert_eq!(unused[0].code, "SYSML050");
    }

    #[test]
    fn disable_next_line_skips_blank() {
        let mut diagnostics = vec![make_diag(7, "SYSML041")];
        let mut suppressions = vec![Suppression {
            directive_line: 5,
            directive_column: 1,
            applies_to_line: SuppressionScope::NextNonBlankLine {
                directive_line: 5,
            },
            rules: SuppressionRules::All,
            used: false,
        }];
        // Non-blank lines: 3, 5, 7 — directive on 5, next is 7.
        let unused = apply_suppressions(&mut diagnostics, &mut suppressions, &[3, 5, 7], Path::new("/x"));
        assert_eq!(diagnostics.len(), 1);
        assert!(diagnostics[0].is_suppressed());
        assert!(unused.is_empty());
    }

    #[test]
    fn non_matching_rule_is_not_suppressed() {
        let mut diagnostics = vec![make_diag(5, "SYSML040")];
        let mut suppressions = vec![Suppression {
            directive_line: 5,
            directive_column: 1,
            applies_to_line: SuppressionScope::SameLine(5),
            rules: SuppressionRules::Specific(vec!["SYSML041".into()]),
            used: false,
        }];
        let unused = apply_suppressions(&mut diagnostics, &mut suppressions, &[5], Path::new("/x"));
        assert_eq!(diagnostics.len(), 1);
        assert!(!diagnostics[0].is_suppressed());
        assert_eq!(unused.len(), 1);
        assert_eq!(unused[0].code, "SYSML050");
    }
}
